language: scala
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk11
matrix:
  exclude:
    - jdk: oraclejdk11
      scala: 2.10.7
    - jdk: oraclejdk11
      scala: 2.11.12
